// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: pb/property.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Property_FindByID_FullMethodName                   = "/hausops.mono.services.property.Property/FindByID"
	Property_List_FullMethodName                       = "/hausops.mono.services.property.Property/List"
	Property_CreateSingleFamilyProperty_FullMethodName = "/hausops.mono.services.property.Property/CreateSingleFamilyProperty"
	Property_CreateMultiFamilyProperty_FullMethodName  = "/hausops.mono.services.property.Property/CreateMultiFamilyProperty"
)

// PropertyClient is the client API for Property service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropertyClient interface {
	FindByID(ctx context.Context, in *PropertyIDRequest, opts ...grpc.CallOption) (*PropertyResponse, error)
	List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Property_ListClient, error)
	CreateSingleFamilyProperty(ctx context.Context, in *SingleFamilyPropertyRequest, opts ...grpc.CallOption) (*SingleFamilyProperty, error)
	CreateMultiFamilyProperty(ctx context.Context, in *MultiFamilyPropertyRequest, opts ...grpc.CallOption) (*MultiFamilyProperty, error)
}

type propertyClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyClient(cc grpc.ClientConnInterface) PropertyClient {
	return &propertyClient{cc}
}

func (c *propertyClient) FindByID(ctx context.Context, in *PropertyIDRequest, opts ...grpc.CallOption) (*PropertyResponse, error) {
	out := new(PropertyResponse)
	err := c.cc.Invoke(ctx, Property_FindByID_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyClient) List(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Property_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &Property_ServiceDesc.Streams[0], Property_List_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &propertyListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Property_ListClient interface {
	Recv() (*PropertyResponse, error)
	grpc.ClientStream
}

type propertyListClient struct {
	grpc.ClientStream
}

func (x *propertyListClient) Recv() (*PropertyResponse, error) {
	m := new(PropertyResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *propertyClient) CreateSingleFamilyProperty(ctx context.Context, in *SingleFamilyPropertyRequest, opts ...grpc.CallOption) (*SingleFamilyProperty, error) {
	out := new(SingleFamilyProperty)
	err := c.cc.Invoke(ctx, Property_CreateSingleFamilyProperty_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyClient) CreateMultiFamilyProperty(ctx context.Context, in *MultiFamilyPropertyRequest, opts ...grpc.CallOption) (*MultiFamilyProperty, error) {
	out := new(MultiFamilyProperty)
	err := c.cc.Invoke(ctx, Property_CreateMultiFamilyProperty_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyServer is the server API for Property service.
// All implementations must embed UnimplementedPropertyServer
// for forward compatibility
type PropertyServer interface {
	FindByID(context.Context, *PropertyIDRequest) (*PropertyResponse, error)
	List(*Empty, Property_ListServer) error
	CreateSingleFamilyProperty(context.Context, *SingleFamilyPropertyRequest) (*SingleFamilyProperty, error)
	CreateMultiFamilyProperty(context.Context, *MultiFamilyPropertyRequest) (*MultiFamilyProperty, error)
	mustEmbedUnimplementedPropertyServer()
}

// UnimplementedPropertyServer must be embedded to have forward compatible implementations.
type UnimplementedPropertyServer struct {
}

func (UnimplementedPropertyServer) FindByID(context.Context, *PropertyIDRequest) (*PropertyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByID not implemented")
}
func (UnimplementedPropertyServer) List(*Empty, Property_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPropertyServer) CreateSingleFamilyProperty(context.Context, *SingleFamilyPropertyRequest) (*SingleFamilyProperty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSingleFamilyProperty not implemented")
}
func (UnimplementedPropertyServer) CreateMultiFamilyProperty(context.Context, *MultiFamilyPropertyRequest) (*MultiFamilyProperty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMultiFamilyProperty not implemented")
}
func (UnimplementedPropertyServer) mustEmbedUnimplementedPropertyServer() {}

// UnsafePropertyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyServer will
// result in compilation errors.
type UnsafePropertyServer interface {
	mustEmbedUnimplementedPropertyServer()
}

func RegisterPropertyServer(s grpc.ServiceRegistrar, srv PropertyServer) {
	s.RegisterService(&Property_ServiceDesc, srv)
}

func _Property_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropertyIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Property_FindByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).FindByID(ctx, req.(*PropertyIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Property_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PropertyServer).List(m, &propertyListServer{stream})
}

type Property_ListServer interface {
	Send(*PropertyResponse) error
	grpc.ServerStream
}

type propertyListServer struct {
	grpc.ServerStream
}

func (x *propertyListServer) Send(m *PropertyResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Property_CreateSingleFamilyProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingleFamilyPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).CreateSingleFamilyProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Property_CreateSingleFamilyProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).CreateSingleFamilyProperty(ctx, req.(*SingleFamilyPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Property_CreateMultiFamilyProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiFamilyPropertyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).CreateMultiFamilyProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Property_CreateMultiFamilyProperty_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).CreateMultiFamilyProperty(ctx, req.(*MultiFamilyPropertyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Property_ServiceDesc is the grpc.ServiceDesc for Property service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Property_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hausops.mono.services.property.Property",
	HandlerType: (*PropertyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindByID",
			Handler:    _Property_FindByID_Handler,
		},
		{
			MethodName: "CreateSingleFamilyProperty",
			Handler:    _Property_CreateSingleFamilyProperty_Handler,
		},
		{
			MethodName: "CreateMultiFamilyProperty",
			Handler:    _Property_CreateMultiFamilyProperty_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _Property_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/property.proto",
}
