name: services/auth-svc

on:
  pull_request:
    paths:
      - services/auth-svc/**

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: services/auth-svc
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache-dependency-path: go.sum
      - run: go mod download
      - run: go test ./...
      - run: go vet ./...
