name: services/property-svc

on:
  pull_request:
    paths:
      - services/property-svc/**

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: services/property-svc
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
          cache-dependency-path: services/property-svc/go.sum
      - run: go test ./...
      - run: go vet ./...
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: 2022.1.3
